<a href="https://colab.research.google.com/github/Acelawen/LongH_IT262/blob/main/CPM_PERT_Shortened.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

simulationDF=pd.read_csv("/content/drive/MyDrive/IT 262/simulationDataset.csv")
simulationDF.head(2)

,A,B,C,D,E,F,G,H,I,J,EOP
0,6.01014,5.261684,4.396674,2.829221,7.591734,4.290677,3.718586,5.519902,11.236210,2.158747,NaN
1,4.91221,5.425116,3.128934,2.976613,5.778138,3.213182,3.762987,2.407435,10.615683,3.163177,NaN

In [5]:
paths = ['ADEJ', 'BCDEJ', 'BCFGJ', 'BCFHJ', 'BI']
pathsDF = pd.DataFrame(columns=paths)
ADEJ=[]
BCDEJ=[]
BCFGJ=[]
BCFHJ=[]
BI=[]
for index, row in simulationDF.iterrows():
  ADEJ.append(row['A']+row['D']+row['E']+row['J'])
  BCDEJ.append(row['B']+row['C']+row['D']+row['E']+row['J'])
  BCFGJ.append(row['B']+row['C']+row['F']+row['G']+row['J'])
  BCFHJ.append(row['B']+row['C']+row['F']+row['H']+row['J'])
  BI.append(row['B']+row['I'])

pathsDF['ADEJ'] = ADEJ
pathsDF['BCDEJ'] = BCDEJ
pathsDF['BCFGJ'] = BCFGJ
pathsDF['BCFHJ'] = BCFHJ
pathsDF['BI'] = BI
print(pathsDF.head(2))

pathsDF['critical'] = pathsDF.idxmax(axis=1)

print(pathsDF.critical.value_counts())

        ADEJ      BCDEJ      BCFGJ      BCFHJ         BI
0  18.589842  22.238060  19.826369  21.627684  16.497894
1  16.830137  20.471978  18.693396  17.337845  16.040799
BCDEJ    33938
BCFGJ    25589
BI       21826
BCFHJ    14796
ADEJ      3851
Name: critical, dtype: int64